Fix issues with api clients looking for Rails.logger
The API clients initial configuration looks to see if Rails constant is
defined and if it is will use Rails.logger.  Since we hack
Rails::VERSION but do not set Rails.logger this causes any OpenAPI
clients to throw an exception on initial configuration:

lib/sources-api-client/configuration.rb:146:in `initialize':
  undefined method `logger' for Rails:Module (NoMethodError)