TopologicalInventory::Api was failing to load due to missing gem
LoadError: cannot load such file -- acts-as-taggable-on
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:256:in `block in load_dependency'
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:662:in `new_constants_in'
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:256:in `load_dependency'
/home/bdunne/.gem/ruby/2.4.3/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/home/bdunne/.gem/ruby/2.4.3/bundler/gems/topological_inventory-core-5467994f6246/app/models/application_record.rb:2:in `<class:ApplicationRecord>'
/home/bdunne/.gem/ruby/2.4.3/bundler/gems/topological_inventory-core-5467994f6246/app/models/application_record.rb:1:in `<top (required)>'